version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: todo-list-rest-api-app
    restart: "always"
    env_file:
      - .env.prod
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mysql
    container_name: todo-list-rest-api-db
    privileged: true
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TODO_LIST_REST_API
    volumes:
      - ./storage:/var/lib/mysql
